# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = ["xhci_pci" "ehci_pci" "ata_piix" "usb_storage" "sd_mod"];
      kernelModules = [];
    };
    kernelModules = ["kvm-intel"];
    extraModulePackages = [];
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/48c2f34c-496e-42c0-96af-f7be80b7d23f";
      fsType = "ext4";
    };
    "/boot" = {
      device = "/dev/disk/by-uuid/FF88-5020";
      fsType = "vfat";
      options = ["fmask=0077" "dmask=0077"];
    };
    "/export" = {
      device = "/dev/disk/by-uuid/6aabc684-9b5a-41e0-ac4a-d7332400a6b8";
      fsType = "btrfs";
    };
  };
  swapDevices = [];
  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
