name = "akhlus"
author = "akhlus"
opacity = "FF" # hex code for opacity
[dark]
# backgrounds
base00 = "#101010"       # default
base01 = "#202020"       # lighter
base02 = "#323232"       # selection
base03 = "#454545"       # comments
# foreground
base04 = "#5c5c5c"       # text_alt
base05 = "#e7e7e7"       # text
base06 = "#f0f0f0"       # bright foreground
base07 = "#ffffff"       # brightest foreground
# colours
base08 = "#FF5964"       # red
base09 = "#F89777"       # orange
base0A = "#F8D353"       # yellow
base0B = "#06D6A0"       # green
base0C = "#72E9C5"       # cyan
base0D = "#5EB0FC"       # blue
base0E = "#9E72E9"       # magenta
base0F = "#D0A5C0"       # violet

[light]
base00 = "#f0f0f0"       # default
base01 = "#eaeaea"       # lighter
base02 = "#dddddd"       # selection
base03 = "#cacaca"       # comments
# foreground
base04 = "#5c5c5c"       # text_alt
base05 = "#323232"       # text
base06 = "#161616"       # bright foreground
base07 = "#101010"       # brightest foreground
# colours
base08 = "#FF5964"       # red
base09 = "#FE640B"       # orange
base0A = "#E8C343"       # yellow
base0B = "#40A02B"       # green
base0C = "#179299"       # cyan
base0D = "#5EB0FC"       # blue
base0E = "#9E72E9"       # magenta
base0F = "#EA76CB"       # violet
